### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by roswitina** [Rohde-Schwarz-Cybersecurity/PanBox#83]
Is Panbox dead or still being developed?

**Comment by caschulz88** [comment]
Yes, it definitely is still being developed!

We are working behind the scenes to announce some pretty cool, new features and a lot more.

**Comment by dhcgn** [comment]
@caschulz88 It would be nice to see an road map or similar to see wehre PanBox is going, Maybe you underrated the interst, but there a lot of people who still searching an alternative to BoxCrypter, et cetera .

**Comment by caschulz88** [comment]
Hi, sorry for the delayed answer. Currently I cannot publish any official agenda, but we want to publish it in early 2017 so please be patient.

**Comment by roswitina** [comment]
When is early 2017?

**Comment by caschulz88** [comment]
Development is still running. As we had several issues there we are still moving the release to a later date. Please understand that the new version will have a complete refactoring so that it took way more time than expected.
